package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoringWeights) DeepCopyInto(out *ScoringWeights) {
	*out = *in
	if in.WeightCPU != nil {
		in, out := &in.WeightCPU, &out.WeightCPU
		*out = new(float64)
		**out = **in
	}
	if in.WeightMemory != nil {
		in, out := &in.WeightMemory, &out.WeightMemory
		*out = new(float64)
		**out = **in
	}
	if in.WeightIdle != nil {
		in, out := &in.WeightIdle, &out.WeightIdle
		*out = new(float64)
		**out = **in
	}
	if in.WeightBenefit != nil {
		in, out := &in.WeightBenefit, &out.WeightBenefit
		*out = new(float64)
		**out = **in
	}
	if in.WeightReplica != nil {
		in, out := &in.WeightReplica, &out.WeightReplica
		*out = new(float64)
		**out = **in
	}
	if in.WeightPriority != nil {
		in, out := &in.WeightPriority, &out.WeightPriority
		*out = new(float64)
		**out = **in
	}
	if in.WeightPDB != nil {
		in, out := &in.WeightPDB, &out.WeightPDB
		*out = new(float64)
		**out = **in
	}
	if in.WeightState != nil {
		in, out := &in.WeightState, &out.WeightState
		*out = new(float64)
		**out = **in
	}
	if in.WeightCheckpoint != nil {
		in, out := &in.WeightCheckpoint, &out.WeightCheckpoint
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoringWeights.
func (in *ScoringWeights) DeepCopy() *ScoringWeights {
	if in == nil {
		return nil
	}
	out := new(ScoringWeights)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoreThresholds) DeepCopyInto(out *ScoreThresholds) {
	*out = *in
	if in.FullReclaimThreshold != nil {
		in, out := &in.FullReclaimThreshold, &out.FullReclaimThreshold
		*out = new(float64)
		**out = **in
	}
	if in.SoftReclaimThreshold != nil {
		in, out := &in.SoftReclaimThreshold, &out.SoftReclaimThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoreThresholds.
func (in *ScoreThresholds) DeepCopy() *ScoreThresholds {
	if in == nil {
		return nil
	}
	out := new(ScoreThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimPolicySpec) DeepCopyInto(out *ReclaimPolicySpec) {
	*out = *in
	if in.CPUIdleThresholdPct != nil {
		in, out := &in.CPUIdleThresholdPct, &out.CPUIdleThresholdPct
		*out = new(float64)
		**out = **in
	}
	if in.MemoryIdleThresholdPct != nil {
		in, out := &in.MemoryIdleThresholdPct, &out.MemoryIdleThresholdPct
		*out = new(float64)
		**out = **in
	}
	if in.QPSIdleThreshold != nil {
		in, out := &in.QPSIdleThreshold, &out.QPSIdleThreshold
		*out = new(float64)
		**out = **in
	}
	if in.NetIdleThresholdBytes != nil {
		in, out := &in.NetIdleThresholdBytes, &out.NetIdleThresholdBytes
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicasRequired != nil {
		in, out := &in.MinReplicasRequired, &out.MinReplicasRequired
		*out = new(int32)
		**out = **in
	}
	if in.MaxPriorityForReclaim != nil {
		in, out := &in.MaxPriorityForReclaim, &out.MaxPriorityForReclaim
		*out = new(int32)
		**out = **in
	}
	if in.ExemptPriorityClasses != nil {
		in, out := &in.ExemptPriorityClasses, &out.ExemptPriorityClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = new(ScoringWeights)
		(*in).DeepCopyInto(*out)
	}
	if in.ScoreThresholds != nil {
		in, out := &in.ScoreThresholds, &out.ScoreThresholds
		*out = new(ScoreThresholds)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimPolicySpec.
func (in *ReclaimPolicySpec) DeepCopy() *ReclaimPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ReclaimPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimPolicyStatus) DeepCopyInto(out *ReclaimPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimPolicyStatus.
func (in *ReclaimPolicyStatus) DeepCopy() *ReclaimPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ReclaimPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimPolicy) DeepCopyInto(out *ReclaimPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimPolicy.
func (in *ReclaimPolicy) DeepCopy() *ReclaimPolicy {
	if in == nil {
		return nil
	}
	out := new(ReclaimPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimPolicyList) DeepCopyInto(out *ReclaimPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReclaimPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimPolicyList.
func (in *ReclaimPolicyList) DeepCopy() *ReclaimPolicyList {
	if in == nil {
		return nil
	}
	out := new(ReclaimPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRecordSpec) DeepCopyInto(out *CheckpointRecordSpec) {
	*out = *in
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
	if in.OriginalRequests != nil {
		in, out := &in.OriginalRequests, &out.OriginalRequests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.OriginalLimits != nil {
		in, out := &in.OriginalLimits, &out.OriginalLimits
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRecordSpec.
func (in *CheckpointRecordSpec) DeepCopy() *CheckpointRecordSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRecordStatus) DeepCopyInto(out *CheckpointRecordStatus) {
	*out = *in
	if in.RestoredAt != nil {
		in, out := &in.RestoredAt, &out.RestoredAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRecordStatus.
func (in *CheckpointRecordStatus) DeepCopy() *CheckpointRecordStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRecord) DeepCopyInto(out *CheckpointRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRecord.
func (in *CheckpointRecord) DeepCopy() *CheckpointRecord {
	if in == nil {
		return nil
	}
	out := new(CheckpointRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRecordList) DeepCopyInto(out *CheckpointRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CheckpointRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRecordList.
func (in *CheckpointRecordList) DeepCopy() *CheckpointRecordList {
	if in == nil {
		return nil
	}
	out := new(CheckpointRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
