apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce
  labels:
    app: user-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: user-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        scheduler.reclaim/class: "B"
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: SERVICE_NAME
              value: "user-service"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: postgres-password
            - name: DB_NAME
              value: "ecommerce"
            - name: JWT_SECRET
              value: "super-secret-key"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /api/users/health
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/users/health
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 15
