apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  postgres-password: "postgres-secure-password"
  mongo-password: "mongo-secure-password"
